/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gametest;

import java.awt.Color;
import javax.swing.JOptionPane;



/**
 *
 * @author ACER-PC
 */
public class WarmCold extends javax.swing.JFrame {

    /**
     * Creates new form TwoD
     */
    public WarmCold() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 1000));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 1000));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jPanel2.setFocusable(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(468, 468, 468)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(482, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(543, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(407, 407, 407))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        int x = evt.getX() - 8;
        int y = evt.getY() - 31;
        jPanel2.setLocation(x, y);
        /*if (x < 333){
            if (y < 333)
                System.out.print("Upper Left");
            else if (y > 666)
                System.out.print("Lower Left");
            else
                System.out.print("Middle Left");
        } else if (x > 666){
            if (y < 333)
                System.out.print("Upper Right");
            else if (y > 666)
                System.out.print("Lower Right");
            else
                System.out.print("Middle Right");
        } else {
            if (y < 333)
                System.out.print("Middle Up");
            else if (y > 666)
                System.out.print("Middle Down");
            else
                System.out.print("Middle");
        }
        System.out.println(" (" + evt.getX() + ", " + evt.getY() + ")");
        */
    }//GEN-LAST:event_formMouseMoved

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        click++;
        int x = (evt.getX() - 8);
        int y = (evt.getY() - 31);
        
        //coldest = >500 , colder = >250, cold = >125, warm = > 62, warmer = >31, warmest = <=31
        
        int xDistance = (x - xGuess);
        int yDistance = (y - yGuess);
        
        if (xDistance < 0)
            xDistance *= -1;
        if (yDistance < 0)
            yDistance *= -1;
        
        int temp = distanceTemp(xDistance + yDistance);
        
        switch (temp) {
            case 6:
                System.out.println("COLDEST\t(" + x + ", " + y + ")");
                jPanel1.setBackground(new Color(0, 255, 255));
                break;
            case 5:
                System.out.println("COLDER\t(" + x + ", " + y + ")");
                jPanel1.setBackground(new Color(0, 125, 255));
                break;
            case 4:
                System.out.println("COLD\t(" + x + ", " + y + ")");
                jPanel1.setBackground(new Color(0, 0, 255));
                break;
            case 3:
                System.out.println("WARM\t(" + x + ", " + y + ")");
                jPanel1.setBackground(new Color(255, 255, 0));
                break;
            case 2:
                System.out.println("WARMER\t(" + x + ", " + y + ")");
                jPanel1.setBackground(new Color(255, 125, 0));
                break;
            case 1:
                System.out.println("WARMEST\t(" + x + ", " + y + ")");
                jPanel1.setBackground(new Color(255, 0, 0));
                if (click < pb)
                    pb = click;
                conf = JOptionPane.showConfirmDialog(null, "You Won!\nIt took you " + click +" times!\n\nHIGHSCORE: " + pb + "\n\nPlay Again?", "Congratulations!", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
                if (conf == 0) {
                    gameReset();
                    randomGuess();
                } else
                    System.exit(0);
                break;
        }
        if (help == 1)
            System.out.println("Distance: " + xDistance + ", " + yDistance);
        else
            if (click % 20 == 0 && click / 20 > 0)
                JOptionPane.showMessageDialog(null, "Press H to toggle help!", "Too Hard?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_formMousePressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == 'h' || evt.getKeyChar() == 'H') {
            help *= -1;
            if (help == -1)
                System.out.println("\nHELP OFF\n");
            else
                System.out.println("\nHELP ON\n");
        }
        
    }//GEN-LAST:event_formKeyPressed

    public static int distanceTemp(int distance) {
        int a = 1000;
        for (int i = 6; i > 0; i--) {
            a /= 2;
            if (i == 1)
                return i;
            else if (distance > a)
                return i;
        }
        return 0;
    }
    public static void randomGuess() {
        int x = (int)(Math.random()* 1000) + 1;
        int y = (int)(Math.random()* 1000) + 1;
        xGuess = x;
        yGuess = y;
    }
    public static void gameReset() {
        WarmCold obj = new WarmCold();
        obj.jPanel1.setBackground(new Color(0,102,51));
        xGuess = 0;
        yGuess = 0;
        conf = -1;
        click = 0;
    }
    
    //variables
    static int xGuess;
    static int yGuess;
    static int conf;
    static int click;
    static int pb = 1000;
    static int help = -1;
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        gameReset();
        randomGuess();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WarmCold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WarmCold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WarmCold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WarmCold.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WarmCold().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
