/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jumpsearch;

/**
 *
 * @author ACER-PC
 */
public class JumpSearchGUI extends javax.swing.JFrame {

    /**
     * Creates new form JumpSearchGUI
     */
    public JumpSearchGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tfNumber = new javax.swing.JTextField();
        lbNumber = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tfKey = new javax.swing.JTextField();
        lKey = new javax.swing.JLabel();
        btnKey = new javax.swing.JButton();
        tfArray = new javax.swing.JTextField();
        tfResult = new javax.swing.JTextField();
        btnRestart = new javax.swing.JButton();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jump Search");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(103, 40, 48));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        jPanel2.setBackground(new java.awt.Color(144, 129, 132));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));

        tfNumber.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        tfNumber.setForeground(new java.awt.Color(124, 36, 20));
        tfNumber.setPreferredSize(new java.awt.Dimension(200, 60));
        tfNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumberActionPerformed(evt);
            }
        });

        lbNumber.setFont(new java.awt.Font("Goudy Old Style", 1, 40)); // NOI18N
        lbNumber.setForeground(new java.awt.Color(17, 17, 12));
        lbNumber.setText("Number:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbNumber)
                .addGap(8, 8, 8)
                .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbNumber))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tfNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBackground(new java.awt.Color(144, 129, 132));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 96));

        tfKey.setFont(new java.awt.Font("Goudy Old Style", 0, 24)); // NOI18N
        tfKey.setForeground(new java.awt.Color(124, 36, 20));
        tfKey.setPreferredSize(new java.awt.Dimension(100, 56));

        lKey.setFont(new java.awt.Font("Goudy Old Style", 1, 36)); // NOI18N
        lKey.setForeground(new java.awt.Color(17, 17, 12));
        lKey.setText("Key:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lKey)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lKey)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(tfKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btnKey.setBackground(new java.awt.Color(151, 135, 62));
        btnKey.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        btnKey.setForeground(new java.awt.Color(17, 17, 12));
        btnKey.setText("Find Key");
        btnKey.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeyActionPerformed(evt);
            }
        });

        tfArray.setFont(new java.awt.Font("Goudy Old Style", 0, 18)); // NOI18N
        tfArray.setForeground(new java.awt.Color(124, 36, 20));
        tfArray.setText("Array: ");
        tfArray.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfArray.setFocusable(false);
        tfArray.setPreferredSize(new java.awt.Dimension(400, 30));

        tfResult.setBackground(new java.awt.Color(144, 129, 132));
        tfResult.setFont(new java.awt.Font("Goudy Old Style", 0, 36)); // NOI18N
        tfResult.setForeground(new java.awt.Color(17, 17, 12));
        tfResult.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfResult.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tfResult.setFocusable(false);
        tfResult.setPreferredSize(new java.awt.Dimension(400, 60));

        btnRestart.setBackground(new java.awt.Color(151, 135, 62));
        btnRestart.setFont(new java.awt.Font("Goudy Old Style", 1, 24)); // NOI18N
        btnRestart.setForeground(new java.awt.Color(17, 17, 12));
        btnRestart.setText("Restart");
        btnRestart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRestart)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKey)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfArray, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKey)
                .addGap(57, 57, 57)
                .addComponent(tfResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRestart)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public int jumpSearch() {
        int n = array.length;
        int step = (int)Math.sqrt(array.length);    //step is the jump per index
        int prev = 0;   //stores the previous jump index
        
        for (int j = step; array[j] < key;) {
            if (array[j] == key) {
                return j;
            }
            prev = (j + 1); //inc by one since it is confirmed that i is not the position of x
            j+=step;        //inc is moved here since if array is out of bounds we can break it without triggering the ArrayOutOfBounds Exception in line 16
            if (j >= n) {
                break;
            }
        }
        
        while (array[prev] < key) {
            prev++;
        }
        
        if (array[prev] == key) {
                return prev;
            }
        return - 1;
    }
    public  int isKeyInArray(int x) {
        for (int j = 0; j < array.length; j++) {
            if (array[j] != x) {
                if (j == (array.length - 1)) {
                    return -1;
                }
                continue;
            }
            break;
        }
        return x;
    }
    public void reset() {
        array = new int[0];
        key = 0;
        i = 0;
        
        tfArray.setText("Array: ");
        tfNumber.setText(null);
        tfKey.setText(null);
        tfResult.setText(null);
    }
    
    int[] array = new int[0];
    int key;
    int i = 0;
    
    private void tfNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumberActionPerformed
        i++;
        array = java.util.Arrays.copyOf(array, i);
        array[i-1] = Integer.parseInt(tfNumber.getText());
        if (i == 1) {
            tfArray.setText(tfArray.getText() + tfNumber.getText());
        } else {
            tfArray.setText(tfArray.getText() + ", " + tfNumber.getText());
        }
        tfNumber.setText(null);
    }//GEN-LAST:event_tfNumberActionPerformed
    
    private void btnKeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeyActionPerformed
        try {
            int x = Integer.parseInt(tfKey.getText());
            tfKey.setText(null);
            key = isKeyInArray(x);
        
            if (key == -1) {
                tfResult.setText(x + " is not in the array");
            } else {
                int ret = jumpSearch();
                if (ret == -1){
                    tfResult.setText("Array is not sorted!");
                } else {
                    tfResult.setText(String.valueOf("Key " + key + " is at position " + ret));
                }
            }
        } catch (Exception e) {
            tfResult.setText("Error");
        }
    }//GEN-LAST:event_btnKeyActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
        reset();
    }//GEN-LAST:event_btnRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JumpSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JumpSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JumpSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JumpSearchGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JumpSearchGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKey;
    private javax.swing.JButton btnRestart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lKey;
    private javax.swing.JLabel lbNumber;
    private javax.swing.JTextField tfArray;
    private javax.swing.JTextField tfKey;
    private javax.swing.JTextField tfNumber;
    private javax.swing.JTextField tfResult;
    // End of variables declaration//GEN-END:variables
}
