/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.esparasproject;

import java.awt.Color;
import java.text.DecimalFormat;
public class LabActivity3 extends javax.swing.JFrame {

    /**
     * Creates new form LabActivity3
     */
    public LabActivity3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        display = new javax.swing.JTextField();
        delete = new javax.swing.JButton();
        divide = new javax.swing.JButton();
        multiply = new javax.swing.JButton();
        subtract = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        add = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        zero = new javax.swing.JButton();
        dot = new javax.swing.JButton();
        history = new javax.swing.JTextField();
        del = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 600));

        display.setBackground(new java.awt.Color(0, 102, 0));
        display.setFont(new java.awt.Font("OCR A Extended", 0, 48)); // NOI18N
        display.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        display.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        display.setFocusable(false);
        display.setPreferredSize(new java.awt.Dimension(450, 100));
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        delete.setBackground(new java.awt.Color(0, 0, 0));
        delete.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 102, 0));
        delete.setText("C");
        delete.setPreferredSize(new java.awt.Dimension(90, 75));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        divide.setBackground(new java.awt.Color(0, 0, 0));
        divide.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        divide.setForeground(new java.awt.Color(255, 102, 0));
        divide.setText("/");
        divide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divideActionPerformed(evt);
            }
        });

        multiply.setBackground(new java.awt.Color(0, 0, 0));
        multiply.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        multiply.setForeground(new java.awt.Color(255, 102, 0));
        multiply.setText("*");
        multiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyActionPerformed(evt);
            }
        });

        subtract.setBackground(new java.awt.Color(0, 0, 0));
        subtract.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        subtract.setForeground(new java.awt.Color(255, 102, 0));
        subtract.setText("-");
        subtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subtractActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(0, 0, 0));
        seven.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        seven.setForeground(new java.awt.Color(0, 0, 255));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(0, 0, 0));
        eight.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        eight.setForeground(new java.awt.Color(0, 0, 255));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(0, 0, 0));
        nine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        nine.setForeground(new java.awt.Color(0, 0, 255));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(0, 0, 0));
        add.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        add.setForeground(new java.awt.Color(0, 255, 0));
        add.setText("+");
        add.setPreferredSize(new java.awt.Dimension(90, 75));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(0, 0, 0));
        four.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        four.setForeground(new java.awt.Color(0, 255, 0));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(0, 0, 0));
        five.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        five.setForeground(new java.awt.Color(0, 255, 0));
        five.setText("5");
        five.setPreferredSize(new java.awt.Dimension(81, 75));
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(0, 0, 0));
        six.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        six.setForeground(new java.awt.Color(0, 255, 0));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        one.setBackground(new java.awt.Color(0, 0, 0));
        one.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        one.setForeground(new java.awt.Color(204, 0, 204));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(0, 0, 0));
        two.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        two.setForeground(new java.awt.Color(204, 0, 204));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(0, 0, 0));
        three.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        three.setForeground(new java.awt.Color(204, 0, 204));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        equal.setBackground(new java.awt.Color(0, 0, 0));
        equal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        equal.setForeground(new java.awt.Color(204, 0, 204));
        equal.setText("=");
        equal.setPreferredSize(new java.awt.Dimension(38, 156));
        equal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalActionPerformed(evt);
            }
        });

        zero.setBackground(new java.awt.Color(0, 0, 0));
        zero.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        zero.setForeground(new java.awt.Color(255, 0, 0));
        zero.setText("0");
        zero.setPreferredSize(new java.awt.Dimension(186, 22));
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        dot.setBackground(new java.awt.Color(0, 0, 0));
        dot.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        dot.setForeground(new java.awt.Color(255, 0, 0));
        dot.setText(".");
        dot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotActionPerformed(evt);
            }
        });

        history.setEditable(false);
        history.setBackground(new java.awt.Color(0, 66, 0));
        history.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        history.setForeground(new java.awt.Color(255, 255, 255));
        history.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        history.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyActionPerformed(evt);
            }
        });

        del.setBackground(new java.awt.Color(0, 0, 0));
        del.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        del.setForeground(new java.awt.Color(255, 102, 0));
        del.setText("Del");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(divide))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(seven)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(eight))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(four)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(multiply)
                                    .addComponent(nine)
                                    .addComponent(six))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtract)
                                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(del)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dot))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(one)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(two)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(three)))
                                .addGap(18, 18, 18)
                                .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {del, delete, divide, dot, eight, equal, five, four, multiply, nine, one, seven, six, subtract, three, two});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(history, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(divide)
                        .addComponent(multiply))
                    .addComponent(del))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seven)
                            .addComponent(eight)
                            .addComponent(nine)
                            .addComponent(subtract))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(four)
                            .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(six)))
                    .addComponent(add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(one)
                            .addComponent(two)
                            .addComponent(three))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dot)
                            .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(equal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {del, delete, divide, eight, four, multiply, nine, seven, subtract});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {dot, five, one, six, three, two, zero});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DecimalFormat form = new DecimalFormat("0.#####");
    double number1, number2;
    boolean m, d, a, s, e;
    boolean n = true;
    
    private static String removeLastChar(String str) {
       return str.substring(0,str.length()-1);
    }
    
    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        display.setText("0");
    }//GEN-LAST:event_displayActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true){
            display.setText(display.getText() + "2");
            history.setText(history.getText() + "2");
        }
    }//GEN-LAST:event_twoActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        if (m == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (m == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 * number2)));
        }
        if (a == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (a == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 + number2)));
        }
        if (s == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (s == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 - number2)));
        }
        if (d == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (d == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 / number2)));
        }
        
        a = true;
        m = false;
        d = false;
        s = false;
        e = false;
        n = false;
        number1 = Double.parseDouble(display.getText());
        history.setText(history.getText() + "+");
    }//GEN-LAST:event_addActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        display.setText("");
        history.setText("");
        number1 = 0;
        number2 = 0;
        m = false;
        d = false;
        a = false;
        s = false;
        e = false;
    }//GEN-LAST:event_deleteActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "1");
            history.setText(history.getText() + "1");
        }
    }//GEN-LAST:event_oneActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "3");
            history.setText(history.getText() + "3");
        }
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "4");
            history.setText(history.getText() + "4");
        }
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "5");
            history.setText(history.getText() + "5");
        }
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "6");
            history.setText(history.getText() + "6");
        }
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "7");
            history.setText(history.getText() + "7");
        }
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "8");
            history.setText(history.getText() + "8");
        }
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "9");
            history.setText(history.getText() + "9");
        }
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + "0");
            history.setText(history.getText() + "0");
        }
    }//GEN-LAST:event_zeroActionPerformed

    private void dotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotActionPerformed
        if (n == false)
            display.setText("");
        n = true;
        if (e == true) {
            display.setText("");
            history.setText("");
            e = false;
            m = false;
            d = false;
            a = false;
            s = false;
        }
        if (n == true) {
            display.setText(display.getText() + ".");
            history.setText(history.getText() + ".");
        }
    }//GEN-LAST:event_dotActionPerformed

    private void divideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divideActionPerformed
        if (m == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (m == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 * number2)));
        }
        if (a == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (a == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 + number2)));
        }
        if (s == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (s == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 - number2)));
        }
        if (d == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (d == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 / number2)));
        }
        
        a = false;
        m = false;
        d = true;
        s = false;
        e = false;
        n = false;
        number1 = Double.parseDouble(display.getText());
        history.setText(history.getText() + "/");
    }//GEN-LAST:event_divideActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        if (m == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (m == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 * number2)));
        }
        if (a == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (a == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 + number2)));
        }
        if (s == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (s == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 - number2)));
        }
        if (d == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (d == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 / number2)));
        }
        
        e = true;
        history.setText(history.getText() + "=");
    }//GEN-LAST:event_equalActionPerformed

    private void multiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyActionPerformed
        if (m == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (m == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 * number2)));
        }
        if (a == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (a == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 + number2)));
        }
        if (s == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (s == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 - number2)));
        }
        if (d == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (d == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 / number2)));
        }
        
        a = false;
        m = true;
        d = false;
        s = false;
        e = false;
        n = false;
        number1 = Double.parseDouble(display.getText());
        history.setText(history.getText() + "*");
    }//GEN-LAST:event_multiplyActionPerformed

    private void subtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subtractActionPerformed
        if (m == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (m == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 * number2)));
        }
        if (a == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (a == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 + number2)));
        }
        if (s == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (s == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 - number2)));
        }
        if (d == true && e == true) {
            number1 = Double.parseDouble(display.getText());
            history.setText(String.valueOf(form.format(number1)));
        } else if (d == true) {
            number2 = Double.parseDouble(display.getText());
            display.setText(String.valueOf(form.format(number1 / number2)));
        }
        
        a = false;
        m = false;
        d = false;
        s = true;
        e = false;
        n = false;
        number1 = Double.parseDouble(display.getText());
        history.setText(history.getText() + "-");
    }//GEN-LAST:event_subtractActionPerformed

    private void historyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_historyActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        if (e == false) {
            display.setText(removeLastChar(display.getText().toString()));
            history.setText(removeLastChar(history.getText().toString()));
        }
    }//GEN-LAST:event_delActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LabActivity3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LabActivity3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LabActivity3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LabActivity3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LabActivity3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton del;
    private javax.swing.JButton delete;
    private javax.swing.JTextField display;
    private javax.swing.JButton divide;
    private javax.swing.JButton dot;
    private javax.swing.JButton eight;
    private javax.swing.JButton equal;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JTextField history;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton multiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton subtract;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
